language: haskell
ghc:
  - "8.2"

# command to build
install:
  - make install
  - make build
  - make clean

# command to run tests
script:
  - ./test
  - HGrammar/HGrammar grammar1
  - HGrammar/HGrammar grammar3
