language: haskell
ghc:
  - "8.2"

# command to build
install:
  - make install
  - make build
  - make clean
  - HGrammar/HGrammar grammar1 grammar1
  - HGrammar/HGrammar grammar2 grammar2
  - HGrammar/HGrammar grammar3 grammar3
  - HGrammar/HGrammar grammar5 grammar5
  - ls
  - make test

# command to run tests
script:
  - ./test
