language: haskell
ghc:
  - "8.2"

# command to build
install:
  - make install
  - make build
  - make clean
  - HGrammar/HGrammar grammar1 grammar1 S
  - HGrammar/HGrammar grammar2 grammar2 S
  - HGrammar/HGrammar grammar3 grammar3 S
  - HGrammar/HGrammar grammar5 grammar5 S
  - ls
  - cat grammar1.hs
  - make test

# command to run tests
script:
  - ./test
